apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-k8s-example
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spring-k8s-example
  template:
    metadata:
      labels:
        name: spring-k8s-example
    spec:
      containers:
        - name: spring-k8s-eample
          image: patilashwin/spring-k8s-example:1.3
          env:
          - name: JAVA_OPTS
            value: "-XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-example-service
spec: 
  type: NodePort
  ports:
   - targetPort: 8090
     port: 8090
  selector:
    name: spring-k8s-example
 
